


#ifndef HULTRASONI_HULTRASONIC_CONFIG_H_
#define HULTRASONI_HULTRASONIC_CONFIG_H_

#define HULTRASONIC_TRIG_PORT	PORTB
#define HULTRASONIC_TRIG_PIN	PIN10
#define HULTRASONIC_ECHO_PORT	PORTA
#define HULTRASONIC_ECHO_PIN	PIN8


#endif /* HULTRASONI_HULTRASONIC_INT_H_ */
